---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: echo-server
  namespace: echo-server
spec:
  chart:
    spec:
      chart: echo-server
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: echo-server
      version: 0.6.0
  interval: 10m0s

