apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: echo-server
  namespace: echo-server
spec:
  test:
    enable: false
  values:
    ingress:
      hosts:
        - host: echo-server.staging
          paths:
            - path: /
              pathType: ImplementationSpecific