apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: echo-server
resources:
  - ../../base/echo-server
patches:
  - path: echo-server-values.yaml
    target:
      kind: HelmRelease