apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/echo-server
namespace: echo-server
patches:
  - path: echo-server-values.yaml
    target:
      kind: HelmRelease
